In [158]:
import pandas as pd

# Read the first 150,000 records

df = pd.read_csv(
    "Car_prices_list_uncleaned.csv",
    nrows=150000
)

print("CSV data:")
print(df)

CSV data:
                                          id  \
0       001c08bb-96f9-4198-a2c9-39bcab088a08
1       00918c06-f736-404a-b55a-0ccd1d876129
2       0083e29f-8030-4478-b662-6dff92e22a06
3       00617c58-7172-49ff-8dc6-cd876ff5f7e8
4       00519a06-60a2-4dea-8431-9ec21add3172
...                                      ...
118377  fffe7230-e0b7-4963-8016-723fa6adf31b
118378  fffe88fe-f83c-4f3a-a9df-5f85c6c55757
118379  ffffb8ef-3895-4963-be87-38d644f2659c
118380  ffffcf58-fe7e-4bda-914b-e17548fd7e82
118381  fffcd44d-aed1-4486-92d2-3fcbaf0fca76

                                              description ratings_average  \
0       Deze Suzuki Swift is maatje S, maar hij valt e...             NaN
1       Kraftvoll, komfortabel, kompromisslos: BMW X3 ...             NaN
2       <strong>Highlights:</strong><br /><ul><li><str...             4,8
3       Veicolo in promozione con la formula &quot;GUI...             4,2
4       De verkoopprijs van deze auto is inclusief een...             NaN
...                                                   ...             ...
118377  Vettura in perfetto stato di carrozzeria, inte...             NaN
118378  <strong>+WILLKOMMEN BEIM AUTOHAUS BAYERNCAR KÖ...             4,5
118379  Verkauft wird ein top gepflegter M235i, welche...             NaN
118380  BMW 840i xDrive Black line<br />Panorama Glasd...             NaN
118381  Auto sempre tagliandata <br />Disponibile per ...             4,9

        ratings_count  ratings_recommend_percentage price_currency   price  \
0                 NaN                           NaN            EUR   22950
1                 NaN                           NaN            EUR   46000
2               124.0                           0.0            EUR  179900
3               253.0                          83.0            EUR   70400
4                 NaN                           NaN            EUR   66999
...               ...                           ...            ...     ...
118377            NaN                           NaN            EUR   49500
118378           59.0                          89.0            EUR   91889
118379            NaN                           NaN            EUR   32900
118380            NaN                           NaN            EUR   57000
118381           44.0                         100.0            EUR   29500

        price_tax_deductible  price_negotiable  price_net  ...      zip  \
0                       True             False    19279.0  ...  8801 PN
1                      False             False        NaN  ...    81476
2                      False             False        NaN  ...     9830
3                       True             False        NaN  ...    30035
4                      False             False        NaN  ...  7121 BG
...                      ...               ...        ...  ...      ...
118377                 False              True        NaN  ...    36063
118378                  True             False        NaN  ...    86343
118379                 False             False        NaN  ...    66740
118380                 False             False        NaN  ...    57078
118381                 False             False        NaN  ...    27010

                         city                     street  latitude longitude  \
0                    FRANEKER             Edisonstraat 1  53.18188   5.52596
1                     München                        NaN  48.09126  11.49140
2          Sint-Martens-Latem     Kortrijksesteenweg 168  51.00730   3.62822
3       Mirano - Venezia - Ve  Via Della Vittoria, 132/A  45.49315  12.12426
4                      AALTEN  Bredevoortsestraatweg 119  51.93223   6.59322
...                       ...                        ...       ...       ...
118377              Marostica                        NaN  45.74450  11.65565
118378            Königsbrunn           Dornierstraße 10  48.25397  10.87116
118379              Saarlouis                        NaN  49.31568   6.75034
118380                Siegen                         NaN  50.91542   8.00146
118381          Bornasco - Pv      Via Giuseppe Verdi, 1  45.26664   9.21795

       seller_is_dealer    seller_type                seller_company_name  \
0                  True         Dealer                    Haaima Franeker
1                 False  PrivateSeller                                NaN
2                  True         Dealer                Garage Vandenberghe
3                  True         Dealer                Ongarato Motors Srl
4                  True         Dealer  Automobielbedrijf Blekkink Aalten
...                 ...            ...                                ...
118377            False  PrivateSeller                                NaN
118378             True         Dealer                     BayernCar GmbH
118379            False  PrivateSeller                                NaN
118380            False  PrivateSeller                                NaN
118381             True         Dealer                        Adrian auto

       has_warranty  warranty
0               NaN       NaN
1               NaN       NaN
2               NaN       NaN
3               NaN       NaN
4               NaN       NaN
...             ...       ...
118377          NaN       NaN
118378          NaN       NaN
118379          NaN       NaN
118380          NaN       NaN
118381          NaN       NaN

[118382 rows x 75 columns]

In [159]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [160]:
file_path = "Car_prices_list_uncleaned.csv"

with open(file_path, "r", encoding="utf-8") as file:
    for i in range(5):
        print(repr(file.readline()))

'id,description,ratings_average,ratings_count,ratings_recommend_percentage,price_currency,price,price_tax_deductible,price_negotiable,price_net,price_vat_rate,vin,make,model,model_version,german_hsn_tsn,mileage_km_raw,mileage_km,registration_date,production_year,vehicle_type,body_type,nr_seats,nr_doors,body_color,paint_type,body_color_original,upholstery,upholstery_color,power_kw,power_hp,transmission,gears,drive_train,cylinders,cylinders_volume_cc,weight_kg,has_particle_filter,fuel_category,primary_fuel,electric_range_km,electric_range_city_km,fuel_cons_comb_l100_km,fuel_cons_city_l100_km,fuel_cons_highway_l100_km,co2_emission_grper_km,fuel_cons_comb_l100_wltp_km,fuel_cons_electric_comb_l100_wltp_km,co2_emission_grper_wltp_km,equipment_comfort,equipment_entertainment,equipment_extra,equipment_safety,is_used,is_new,is_preregistered,had_accident,has_full_service_history,non_smoking,nr_prev_owners,is_rental,envir_standard,original_market,offer_type,country_code,zip,city,street,latitude,longitude,seller_is_dealer,seller_type,seller_company_name,has_warranty,warranty\n'
'001c08bb-96f9-4198-a2c9-39bcab088a08,"Deze Suzuki Swift is maatje S, maar hij valt een stuk ruimer. Behalve in kosten. Zijn pittige prestaties dankt deze auto aan zijn compacte en zuinige motor. Ervaar de weldadige warmte van de inschakelbare stoelverwarming. Bij de uitrusting van deze Suzuki horen onder meer 16 inch lichtmetalen velgen, LED koplampen, warmtewerend glas, dakspoiler, in delen neerklapbare achterbank en LED-achterlichten. <br /><br />Een handige optie is de achteruitrijcamera. Achteruitrijden, inparkeren en manoeuvreren gaat gemakkelijker dan ooit. Adaptive cruise control is een comfortabele en veilige optie. Het systeem reguleert de snelheid en houdt automatisch afstand tot uw voorligger. Connected Services voegt nog meer comfort en veiligheid toe aan deze auto. Deze Suzuki is voorzien van knoppen op het stuur om het full map navigatiesysteem en het audiosysteem met DAB-ontvangst te bedienen. In een auto als deze kunt u niet zonder electronic climate control, zodat de temperatuur altijd goed is. Ook keyless entry, lederen stuur, bagage afdekhoes en boordcomputer horen tot de voorzieningen op deze auto. <br /><br />Deze auto is voorzien van innovatieve systemen die u onderweg begeleiden en beschermen. U rijdt ook veiliger omdat deze auto voor u de verkeersborden langs de weg kan lezen. De belangrijkste borden worden op uw instrumentarium geprojecteerd, zodat u ze niet kunt missen. Mooi binnen de lijnen van de rijstrook blijven? Het Lane-keeping systeem helpt altijd een handje. Bij concentratieverlies van de bestuurder geeft vermoeidheidsherkenning automatisch een waarschuwingssignaal. De auto is ook uitgerust met dodehoekdetectie, hill hold functie, autonoom remsysteem en bandenspanningcontrolesysteem. <br /><br />U bent nieuwsgierig? Bel of mail ons dan direct om een proefrit te reserveren.<br /><br />Autobedrijf Haaima is al decennia lang het vertrouwde adres in Friesland en de Noordoostpolder als het gaat om mobiliteit in de breedste zin van het woord!<br /><br /><strong>Meer informatie</strong><br /><br /><strong>Algemene informatie</strong><br />Modeljaar: <strong>2024</strong><br />Typenummer: <strong>Z12E</strong><br /><br /><strong>Technische informatie</strong><br />Koppel: <strong>112 Nm</strong><br />Tankinhoud: <strong>37 liter</strong><br />Acceleratie (0-100): <strong>12,5 s</strong><br />Topsnelheid: <strong>165 km/u</strong><br /><br /><strong>Maten</strong><br />Afmetingen (LxB): <strong>386 x 174 cm</strong><br />Wielbasis: <strong>245 cm</strong><br /><br /><strong>Gewichten</strong><br />Laadvermogen: <strong>471 kg</strong><br />GVW: <strong>1.365 kg</strong><br />Max. trekgewicht: <strong>1.000 kg</strong> (ongeremd 400 kg)<br /><br /><strong>Interieur</strong><br />Interieurkleur: <strong>Fabric black</strong><br /><br /><strong>Milieu en verbruik</strong><br />Gemiddeld brandstofverbruik: <strong>4,4 l/100km</strong> (1 op 22,7)<br />Energielabel: <strong>A</strong><br /><br /><strong>Financiële informatie</strong><br />Motorrijtuigenbelasting: <strong>€\xa088 - €\xa097</strong> per kwartaal<br /><br /><strong>Beschikbare afleverpakketten:</strong><br /><ul><li><strong>Standaard  (inbegrepen):</strong> Gepoetst, tenaamstelling voertuig, geldige APK, vloeistoffencontrole</li><li><strong>Demo Pack (€\xa0495 meerprijs):</strong> </li></ul>  + Auto&#x27;s tot 1 jaar oud<br />  + Onderhoudsbeurt conform schema<br />  + Poetsen van de auto ( Auto wordt gereconditioneerd en gedesinfecteerd )<br />  + Lopende fabrieksgarantie ( Minimaal 12 maanden )<br />  + Mogelijkheid verlenging fabrieksgarantie ( Vraag naar de voorwaarden )<br />  + 10.000 km of 12 maanden onderhoudsvrij<br />  + Omruilgarantie 14 dagen of 1.000km<br />  + Navigatie update naar meest recente beschikbare software / kaart ( Peugeot, Opel, Nissan &amp; Suzuki )<br />  + 24/7 Pechhulp heel Europa<br />  + 100 punten kwaliteits controle<br />  + Mogelijkheid aflevering aan huis<br />  + Mogelijkheid proefrit aan huis<br />  + Mogelijkheid tot private shoppen buiten openingstijden<br />  Dit afleverpakket bevat (in plaats van afleverpakket &quot;Standaard &quot;): BOVAG 40-Puntencheck; BOVAG Afleverbeurt; Nieuwe APK<br /><br /><br /><strong>Aanvullende opties en accessoires</strong><br /><br /><ul><li>Navigatiesysteem full map</li><li>voorstoelen verwarmd</li><li>achterbank in delen neerklapbaar</li><li>achteruitrij assistent</li><li>achteruitrijcamera</li><li>alarm klasse 1(startblokkering)</li><li>Automatische snelheids begrenzing</li><li>Autonomous Emergency Braking</li><li>bagagedek</li><li>bestuurdersstoel in hoogte verstelbaar</li><li>Bluetooth telefoonvoorbereiding</li><li>buitenspiegels elektrisch inklapbaar</li><li>buitenspiegels elektrisch verstel- en verwarmbaar</li><li>chroom delen interieur</li><li>connected services</li><li>DAB ontvanger</li><li>dakspoiler</li><li>elektrische ramen achter</li><li>elektronische remkrachtverdeling</li><li>Extra getint glas</li><li>glans exterieur delen</li><li>hoofd airbag(s) voor</li><li>keyless start</li><li>kleur parelmoer</li><li>LED achterlichten</li><li>multimedia-voorbereiding</li><li>multimedia scherm klein</li><li>Rijstrooksensor met correctie</li><li>stuur verstelbaar</li><li>warmtewerend glas</li></ul>",,,,EUR,22950,TRUE,FALSE,19279,,,Suzuki,Swift,1.2 Style Smart Hybrid | Navigatie | Cruise contro,,10500,"10,500 km",01-12-2024,,Car,Compact,5,5,Black,Metallic,Super black pearl metallic (zw,Cloth,Black,61,83,Manual,5,Front Wheel Drive,3,1197,894 kg,FALSE,Gasoline,,,,,,,,,,99,"[\'Air conditioning\', \'Automatic climate control\', \'Cruise control\', \'Electrical side mirrors\', \'Hill Holder\', \'Keyless central door lock\', \'Leather steering wheel\', \'Light sensor\', \'Multi-function steering wheel\', \'Navigation system\', \'Park Distance Control\', \'Parking assist system camera\', \'Parking assist system sensors rear\', \'Power windows\', \'Seat heating\', \'Start-stop system\', \'Tinted windows\']","[\'Android Auto\', \'Apple CarPlay\', \'Bluetooth\', \'Digital radio\', \'On-board computer\', \'Radio\']","[\'Alloy wheels (16"")\', \'Spoiler\']","[\'ABS\', \'Adaptive Cruise Control\', \'Alarm system\', \'Blind spot monitor\', \'Daytime running lights\', \'Driver drowsiness detection\', \'Driver-side airbag\', \'Electronic stability control\', \'Glare-free high beam headlights\', \'Head airbag\', \'High beam assist\', \'Immobilizer\', \'LED Daytime Running Lights\', \'LED Headlights\', \'Lane departure warning system\', \'Passenger-side airbag\', \'Power steering\', \'Side airbag\', \'Speed limit control system\', \'Tire pressure monitoring system\', \'Traction control\', \'Traffic sign recognition\']",TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,,FALSE,Euro 6d-TEMP,,U,NL,8801 PN,FRANEKER,Edisonstraat 1,53.18188,5.52596,TRUE,Dealer,Haaima Franeker,,\n'
'00918c06-f736-404a-b55a-0ccd1d876129,"Kraftvoll, komfortabel, kompromisslos: BMW X3 M40i xDrive mit 360 PS und Top-Ausstattung. Perfekter Zustand, unfallfrei, alle Services bei BMW, TÜV bis 06/2027<br /><br />Ich verkaufe meinen BMW X3 M40i xDrive (EZ 03/2020) in sportlichem <strong>Phytonicblau Metallic</strong> mit edlem Leder „Vernasca“ in Schwarz und blauer Kontraststeppung. Der 3,0-Liter-Reihensechszylinder mit <strong>360 PS</strong> und adaptivem M-Fahrwerk garantiert puren Fahrspaß – 0–100 km/h in nur <strong>4,8 Sekunden</strong>.<br />Fahrzeughistorie:<br /><ul><li>Im November 2020 vom BMW Autohaus ohne Vorschäden übernommen (TÜV-Wertgutachten: mängelfrei, 0 € Wertminderung)</li></ul><br /><ul><li>Erstbesitzer: 11.000 km</li></ul><br /><ul><li>Privat gefahren: 45.000 km seit Kauf</li></ul><br /><ul><li>Lückenlos BMW Scheckheft gepflegt</li></ul><br /><ul><li>Absolut unfallfrei, keine Lack- oder Karosserieschäden</li></ul><br /><ul><li>TÜV bis <strong>Juni 2027</strong></li></ul><br />Extras &amp; Ausstattung:<br /><ul><li><strong>Nahezu Vollausstattung</strong> inkl. Entertainment Paket, Business Paket Professional, Innovationspaket, Winterfreude Paket</li></ul><br /><ul><li>Adaptives LED-Lichtsystem</li></ul><br /><ul><li>Driving Assistant Plus</li></ul><br /><ul><li>Parking Assistant Plus (360°-Kamera)</li></ul><br /><ul><li>Harman Kardon Surround Sound System</li></ul><br /><ul><li>Panorama-Glasdach</li></ul><br /><ul><li>Sonnenschutzverglasung</li></ul><br /><ul><li>Anhängerkupplung mit schwenkbarem Kugelkopf</li></ul><br /><ul><li>Adaptives M-Fahrwerk</li></ul><br /><ul><li>Winterkompletträder auf BMW-Alufelgen (identisch zu den Sommerfelgen 20 Zoll Doppelspeiche 699M) im Preis inbegriffen – Winterreifen sollten erneuert werden, Felgen mit leichten Gebrauchsspuren.</li></ul><br />Ich verkaufe schweren Herzens aufgrund eines Dienstwagens – für Liebhaber von Leistung, Komfort und Qualität ein echtes Traumfahrzeug.<br /><br /><br /><strong>Assistenzsysteme<br /></strong>Spracheingabesystem, Head-Up-Display, Müdigkeitserkennung, Spurverlassenswarnung, Surround View, BMW Park Assistent Plus, Rückfahrkamera, Diving Assistent Plus, Aktivie Geschwindkeitsregelung mit Stop &amp; Go, Kollisionswarnung, Verkehrszeichenerkennung<strong><br /></strong><br /><strong>Licht und Sicht</strong><br />Adaptiver LED-Scheinwerfer, Adaptives Kurvenlicht, Tagfahrlicht, LED-Nebelscheinwerfer, Fernlichtassistent, Fahrlichtautomatik, Regensensor, Automatisch abblendende Innen- und Außenspiegel, Sonnen- und Wärmeschutzverglasung, Akustikverglasung, Ambientebeleuchtung, Nebelscheinwerfer<br /><br /><strong>Audio &amp; Kommunikation</strong><br />Multimedia-System, Radio mit MP3, Digitaler Radioempfang DAB, BMW Connected Package Professional, BMW Live Cockpit Professional, Handyvorbereitung Bluetooth, iDrive, Harman Kardon Soundsystem, USB-C Anschluss, Apple CarPlay, Android Auto, Kabelloses Laden für Handys, WLAN Hotspot<br /><br /><strong>Komfort</strong><br />3-Zonen-Klimaautomatik, Panorama-Schiebedach, Fahrer und Beifahrersitz elektrisch einstellbar mit Memory, Lordosenstütze, Sitzheizung vorne, Sportsitze, Armauflagen vorn und Hinten, Standheizung mit Fernbedienung, Servotronic, Variable Sportlenkung, Lenksäule verstellbar, Komfortzugang, Auto Start Stopp Funktion, Zentralverriegelung mit Fernbedienung, BMW Display Key, Fensterheber elektrisch vorn und hinten, Automatische Heckklappe, Fahrprofilauswahl<br /><br /><strong>Interieur</strong><br />Sitze Leder Vernasca Schwarz mit Kontraststeppung blau, Multifunktions-Sport-Lederlenkrad (M), BMW Individual Dachhimmel anthrazit, Instrumententafel in Sensatec, Lenkradheizung, Rücksitze klapp- und teilbar, Laderaumabdeckung, Gepäckraumtrennnetz, Fußmatten in Velours, Abagenpaket, Interieurleisten Aluminium Feinschliff, Galvanikapplikationen für Bedienelemente<br /><br /><strong>Exterieur</strong><br />Adaptives Fahrwerk, Allrad, M Sportdifferenzial, M Sportbremse, M Leichtmetallräder 20 Zoll Doppelspeiche 699M, Außenspiegel elektrisch verstellbar und anklappbar (beheizt), Anhängerkupplung schwenkbar, Dachreling BMW Individual Hochglanz Shadow Line, Innovationspaket, Notrufsystem, Touchscreen Bedienung<br /><br /><strong>Sicherheit</strong><br />Fahrer-/Beifahrerairbag, Kopfairbag vorn und hinten, Seitenairbag vorn, ISOFIX Kindersitzbefestigung, Fußgängerschutzsystem, Dynamische Tranktionskontrolle, Dynamische Stabilitätskontrolle, Reifendruckkontrolle, Diebstahlwarnanlage, Wegfahrsperre, Außentemperaturanzeige, Antiblockiersystem<br /><br /><strong>Weitere Ausstattung</strong><br />Sport-Automatic Getriebe Steptronic mit Schaltwippen, Adaptives Fahrwerk, Performance Control<br />",,,,EUR,46000,FALSE,FALSE,,,,BMW,X3 M,M40i xDrive | nahezu Vollausstattung | Top-Zustand,,55609,"55,609 km",01-03-2020,,Car,Off-Road/Pick-up,5,5,Blue,Metallic,,Full leather,Black,265,360,Automatic,8,4WD,6,2998,"1,945 kg",FALSE,Gasoline,Super E10 95,,,7.8,,,220,,,,"[\'360° camera\', \'Armrest\', \'Automatic climate control, 3 zones\', \'Auxiliary heating\', \'Cruise control\', \'Electric tailgate\', \'Electrical side mirrors\', \'Electrically adjustable seats\', \'Heads-up display\', \'Heated steering wheel\', \'Hill Holder\', \'Keyless central door lock\', \'Leather seats\', \'Leather steering wheel\', \'Light sensor\', \'Lumbar support\', \'Multi-function steering wheel\', \'Navigation system\', \'Panorama roof\', \'Park Distance Control\', \'Parking assist system camera\', \'Parking assist system self-steering\', \'Parking assist system sensors front\', \'Parking assist system sensors rear\', \'Power windows\', \'Rain sensor\', \'Seat heating\', \'Split rear seats\', \'Start-stop system\', \'Sunroof\', \'Tinted windows\']","[\'Android Auto\', \'Apple CarPlay\', \'Bluetooth\', \'Digital cockpit\', \'Digital radio\', \'Hands-free equipment\', \'Induction charging for smartphones\', \'MP3\', \'On-board computer\', \'Radio\', \'Sound system\', \'USB\', \'WLAN / WiFi hotspot\']","[\'Alloy wheels (20"")\', \'Ambient lighting\', \'Automatically dimming interior mirror\', \'Cargo barrier\', \'E10-enabled\', \'Electronic parking brake\', \'Emergency tyre repair kit\', \'Roof rack\', \'Shift paddles\', \'Sport package\', \'Sport seats\', \'Sport suspension\', \'Summer tyres\', \'Touch screen\', \'Trailer hitch\', \'Voice Control\', \'Winter package\', \'Winter tyres\']","[\'ABS\', \'Adaptive Cruise Control\', \'Adaptive headlights\', \'Alarm system\', \'Blind spot monitor\', \'Central door lock with remote control\', \'Daytime running lights\', \'Distance warning system\', \'Driver drowsiness detection\', \'Driver-side airbag\', \'Electronic stability control\', \'Emergency brake assistant\', \'Emergency system\', \'Fog lights\', \'Full-LED headlights\', \'Glare-free high beam headlights\', \'Head airbag\', \'High beam assist\', \'Immobilizer\', \'Isofix\', \'LED Daytime Running Lights\', \'LED Headlights\', \'Lane departure warning system\', \'Passenger-side airbag\', \'Power steering\', \'Rear airbag\', \'Side airbag\', \'Speed limit control system\', \'Tire pressure monitoring system\', \'Traction control\', \'Traffic sign recognition\']",TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,2,FALSE,Euro 6d-TEMP,,U,DE,81476,München,,48.09126,11.4914,FALSE,PrivateSeller,,,\n'
'0083e29f-8030-4478-b662-6dff92e22a06,<strong>Highlights:</strong><br /><ul><li><strong>First Owner</strong></li><li><strong>Porsche maintained</strong></li><li><strong>Low mileage</strong></li><li><strong>100% original paint - PPF on front</strong></li></ul><strong>Opties:</strong><br /><br /><br /><ul><li>039 - Touring Package exterieur in zwart</li><li>082 - 90 liter benzine tank</li><li>342 - Stoelverwarming</li><li>454 - Cruise control</li><li>474 - Liftsysteem vooras</li><li>486 - 6-Versnellings GT-sportschakelbak</li><li>630 - Licht-Design pakket</li><li>7X9 - Achteruitrijcamera</li><li>9VL - BOSE Surround Sound System</li><li>0GJ - Wijzerplaat Sportchrono wit</li><li>EKG - Interieurpakket sierlijsten carbon</li><li>P07 - Adaptieve sporstoelen Plus (18-voudig verstelbaar) met memory pakket</li><li>P13 - Zelfdimmende binnen-/ buitenspiegels met regensensor</li><li>QR5 - Sport Chrono Pakket</li><li>XDK - Wielen zwart zijdeglans gespoten</li><li>XEY - LED- koplampen zwart incl. PDLS+</li><li>XFJ - Wijzerplaten instrumentenpaneel wit</li><li>XPL - Privacy beglazing</li><li>XYB - Tankdop in aluminium look</li></ul><hr /><strong>Nous parlons Français</strong><br /><strong>We speak English</strong><br /><strong>Wir sprechen Deutsch</strong><br /><hr /><strong>Tim:</strong><br /><ul><li>Tel. +32 497/36.50.72</li><li>Mail: tim@garagevandenberghe.be</li></ul>,"4,8",124,0,EUR,179900,FALSE,FALSE,,,WP0ZZZ99ZJS168484,Porsche,991,.2 GT3 TOURING / MANUAL / CHRONO / LIFT / BOSE,,18200,"18,200 km",01-04-2018,,Car,Coupe,2,2,Blue,Metallic,Saphire Blue metallic,Full leather,Black,368,500,Manual,6,Rear Wheel Drive,6,3996,"1,760 kg",FALSE,Gasoline,,,,12.9,,,310,,,,"[\'Air conditioning\', \'Armrest\', \'Automatic climate control\', \'Cruise control\', \'Electrical side mirrors\', \'Electrically adjustable seats\', \'Fold flat passenger seat\', \'Hill Holder\', \'Leather seats\', \'Light sensor\', \'Lumbar support\', \'Navigation system\', \'Park Distance Control\', \'Parking assist system camera\', \'Parking assist system sensors rear\', \'Power windows\', \'Rain sensor\', \'Seat heating\', \'Tinted windows\']","[\'Apple CarPlay\', \'Bluetooth\', \'CD player\', \'Digital radio\', \'Hands-free equipment\', \'MP3\', \'On-board computer\', \'Radio\', \'Sound system\', \'USB\', \'WLAN / WiFi hotspot\']","[\'Alloy wheels (20"")\', \'Ambient lighting\', \'Automatically dimming interior mirror\', \'Electronic parking brake\', \'Headlight washer system\', \'Sport package\', \'Sport seats\', \'Sport suspension\', \'Summer tyres\', \'Touch screen\', \'Voice Control\']","[\'ABS\', \'Alarm system\', \'Central door lock\', \'Central door lock with remote control\', \'Daytime running lights\', \'Driver-side airbag\', \'Electronic stability control\', \'Emergency brake assistant\', \'Fog lights\', \'Full-LED headlights\', \'Glare-free high beam headlights\', \'Head airbag\', \'High beam assist\', \'Immobilizer\', \'LED Daytime Running Lights\', \'Passenger-side airbag\', \'Power steering\', \'Side airbag\', \'Tire pressure monitoring system\']",TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,,FALSE,Euro 6,,U,BE,9830,Sint-Martens-Latem,Kortrijksesteenweg 168,51.0073,3.62822,TRUE,Dealer,Garage Vandenberghe,,\n'

In [161]:
df = pd.read_csv(
    file_path,
    nrows=150000
)

In [162]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 118382 entries, 0 to 118381
Data columns (total 75 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   id                                    118382 non-null  str
 1   description                           113990 non-null  str
 2   ratings_average                       76428 non-null   str
 3   ratings_count                         76428 non-null   float64
 4   ratings_recommend_percentage          76428 non-null   float64
 5   price_currency                        118382 non-null  str
 6   price                                 118382 non-null  int64
 7   price_tax_deductible                  118382 non-null  bool
 8   price_negotiable                      118382 non-null  bool
 9   price_net                             34016 non-null   float64
 10  price_vat_rate                        30379 non-null   float64
 11  vin                                   40222 non-null   str
 12  make                                  118382 non-null  str
 13  model                                 116980 non-null  str
 14  model_version                         117544 non-null  str
 15  german_hsn_tsn                        30811 non-null   str
 16  mileage_km_raw                        117738 non-null  float64
 17  mileage_km                            117738 non-null  str
 18  registration_date                     118161 non-null  str
 19  production_year                       22272 non-null   float64
 20  vehicle_type                          118382 non-null  str
 21  body_type                             118382 non-null  str
 22  nr_seats                              113476 non-null  float64
 23  nr_doors                              116929 non-null  float64
 24  body_color                            106471 non-null  str
 25  paint_type                            92335 non-null   str
 26  body_color_original                   74050 non-null   str
 27  upholstery                            91637 non-null   str
 28  upholstery_color                      85897 non-null   str
 29  power_kw                              116770 non-null  float64
 30  power_hp                              116770 non-null  float64
 31  transmission                          117566 non-null  str
 32  gears                                 75134 non-null   float64
 33  drive_train                           90629 non-null   str
 34  cylinders                             93524 non-null   float64
 35  cylinders_volume_cc                   106096 non-null  float64
 36  weight_kg                             94296 non-null   str
 37  has_particle_filter                   118382 non-null  bool
 38  fuel_category                         118309 non-null  str
 39  primary_fuel                          59973 non-null   str
 40  electric_range_km                     12745 non-null   float64
 41  electric_range_city_km                639 non-null     float64
 42  fuel_cons_comb_l100_km                41844 non-null   float64
 43  fuel_cons_city_l100_km                0 non-null       float64
 44  fuel_cons_highway_l100_km             0 non-null       float64
 45  co2_emission_grper_km                 24811 non-null   float64
 46  fuel_cons_comb_l100_wltp_km           30270 non-null   float64
 47  fuel_cons_electric_comb_l100_wltp_km  4926 non-null    float64
 48  co2_emission_grper_wltp_km            46455 non-null   float64
 49  equipment_comfort                     118382 non-null  str
 50  equipment_entertainment               118382 non-null  str
 51  equipment_extra                       118382 non-null  str
 52  equipment_safety                      118382 non-null  str
 53  is_used                               118382 non-null  bool
 54  is_new                                118382 non-null  bool
 55  is_preregistered                      118382 non-null  bool
 56  had_accident                          118382 non-null  bool
 57  has_full_service_history              118382 non-null  bool
 58  non_smoking                           118382 non-null  bool
 59  nr_prev_owners                        64814 non-null   float64
 60  is_rental                             118382 non-null  bool
 61  envir_standard                        77121 non-null   str
 62  original_market                       45616 non-null   str
 63  offer_type                            118382 non-null  str
 64  country_code                          118367 non-null  str
 65  zip                                   118363 non-null  str
 66  city                                  118274 non-null  str
 67  street                                98054 non-null   str
 68  latitude                              117993 non-null  float64
 69  longitude                             117993 non-null  float64
 70  seller_is_dealer                      118382 non-null  bool
 71  seller_type                           118367 non-null  str
 72  seller_company_name                   98565 non-null   str
 73  has_warranty                          0 non-null       float64
 74  warranty                              0 non-null       float64
dtypes: bool(11), float64(27), int64(1), str(36)
memory usage: 59.0 MB

In [163]:
print("Dataset shape:", df.shape)

Dataset shape: (118382, 75)

In [164]:
print("\nColumn names:")
print(df.columns.tolist())

Column names:
['id', 'description', 'ratings_average', 'ratings_count', 'ratings_recommend_percentage', 'price_currency', 'price', 'price_tax_deductible', 'price_negotiable', 'price_net', 'price_vat_rate', 'vin', 'make', 'model', 'model_version', 'german_hsn_tsn', 'mileage_km_raw', 'mileage_km', 'registration_date', 'production_year', 'vehicle_type', 'body_type', 'nr_seats', 'nr_doors', 'body_color', 'paint_type', 'body_color_original', 'upholstery', 'upholstery_color', 'power_kw', 'power_hp', 'transmission', 'gears', 'drive_train', 'cylinders', 'cylinders_volume_cc', 'weight_kg', 'has_particle_filter', 'fuel_category', 'primary_fuel', 'electric_range_km', 'electric_range_city_km', 'fuel_cons_comb_l100_km', 'fuel_cons_city_l100_km', 'fuel_cons_highway_l100_km', 'co2_emission_grper_km', 'fuel_cons_comb_l100_wltp_km', 'fuel_cons_electric_comb_l100_wltp_km', 'co2_emission_grper_wltp_km', 'equipment_comfort', 'equipment_entertainment', 'equipment_extra', 'equipment_safety', 'is_used', 'is_new', 'is_preregistered', 'had_accident', 'has_full_service_history', 'non_smoking', 'nr_prev_owners', 'is_rental', 'envir_standard', 'original_market', 'offer_type', 'country_code', 'zip', 'city', 'street', 'latitude', 'longitude', 'seller_is_dealer', 'seller_type', 'seller_company_name', 'has_warranty', 'warranty']

In [165]:
print("\nData types:")
display(df.dtypes)

Data types:

id                                  str
description                         str
ratings_average                     str
ratings_count                   float64
ratings_recommend_percentage    float64
                                 ...
seller_is_dealer                   bool
seller_type                         str
seller_company_name                 str
has_warranty                    float64
warranty                        float64
Length: 75, dtype: object

In [166]:
print("\nFirst five records:")
display(df.head())

First five records:

,id,description,ratings_average,ratings_count,ratings_recommend_percentage,price_currency,price,price_tax_deductible,price_negotiable,price_net,...,zip,city,street,latitude,longitude,seller_is_dealer,seller_type,seller_company_name,has_warranty,warranty
0,001c08bb-96f9-4198-a2c9-39bcab088a08,"Deze Suzuki Swift is maatje S, maar hij valt e...",NaN,NaN,NaN,EUR,22950,True,False,19279.0,...,8801 PN,FRANEKER,Edisonstraat 1,53.18188,5.52596,True,Dealer,Haaima Franeker,NaN,NaN
1,00918c06-f736-404a-b55a-0ccd1d876129,"Kraftvoll, komfortabel, kompromisslos: BMW X3 ...",NaN,NaN,NaN,EUR,46000,False,False,NaN,...,81476,München,NaN,48.09126,11.49140,False,PrivateSeller,NaN,NaN,NaN
2,0083e29f-8030-4478-b662-6dff92e22a06,<strong>Highlights:</strong><br /><ul><li><str...,"4,8",124.0,0.0,EUR,179900,False,False,NaN,...,9830,Sint-Martens-Latem,Kortrijksesteenweg 168,51.00730,3.62822,True,Dealer,Garage Vandenberghe,NaN,NaN
3,00617c58-7172-49ff-8dc6-cd876ff5f7e8,Veicolo in promozione con la formula &quot;GUI...,"4,2",253.0,83.0,EUR,70400,True,False,NaN,...,30035,Mirano - Venezia - Ve,"Via Della Vittoria, 132/A",45.49315,12.12426,True,Dealer,Ongarato Motors Srl,NaN,NaN
4,00519a06-60a2-4dea-8431-9ec21add3172,De verkoopprijs van deze auto is inclusief een...,NaN,NaN,NaN,EUR,66999,False,False,NaN,...,7121 BG,AALTEN,Bredevoortsestraatweg 119,51.93223,6.59322,True,Dealer,Automobielbedrijf Blekkink Aalten,NaN,NaN

In [167]:
df.shape

(118382, 75)

In [169]:
missing_values = df.isnull().sum()

display(
    missing_values[missing_values > 0]
    .sort_values(ascending=False)
)

fuel_cons_city_l100_km                  118382
warranty                                118382
has_warranty                            118382
fuel_cons_highway_l100_km               118382
electric_range_city_km                  117743
fuel_cons_electric_comb_l100_wltp_km    113456
electric_range_km                       105637
production_year                          96110
co2_emission_grper_km                    93571
fuel_cons_comb_l100_wltp_km              88112
price_vat_rate                           88003
german_hsn_tsn                           87571
price_net                                84366
vin                                      78160
fuel_cons_comb_l100_km                   76538
original_market                          72766
co2_emission_grper_wltp_km               71927
primary_fuel                             58409
nr_prev_owners                           53568
body_color_original                      44332
gears                                    43248
ratings_count                            41954
ratings_average                          41954
ratings_recommend_percentage             41954
envir_standard                           41261
upholstery_color                         32485
drive_train                              27753
upholstery                               26745
paint_type                               26047
cylinders                                24858
weight_kg                                24086
street                                   20328
seller_company_name                      19817
cylinders_volume_cc                      12286
body_color                               11911
nr_seats                                  4906
description                               4392
power_hp                                  1612
power_kw                                  1612
nr_doors                                  1453
model                                     1402
model_version                              838
transmission                               816
mileage_km_raw                             644
mileage_km                                 644
longitude                                  389
latitude                                   389
registration_date                          221
city                                       108
fuel_category                               73
zip                                         19
country_code                                15
seller_type                                 15
dtype: int64

In [170]:
missing_summary = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage": df.isnull().mean() * 100
})

missing_summary = (
    missing_summary[missing_summary["missing_count"] > 0]
    .sort_values("missing_percentage", ascending=False)
)

display(missing_summary.round(2))

                                      missing_count  missing_percentage
fuel_cons_city_l100_km                       118382              100.00
warranty                                     118382              100.00
has_warranty                                 118382              100.00
fuel_cons_highway_l100_km                    118382              100.00
electric_range_city_km                       117743               99.46
fuel_cons_electric_comb_l100_wltp_km         113456               95.84
electric_range_km                            105637               89.23
production_year                               96110               81.19
co2_emission_grper_km                         93571               79.04
fuel_cons_comb_l100_wltp_km                   88112               74.43
price_vat_rate                                88003               74.34
german_hsn_tsn                                87571               73.97
price_net                                     84366               71.27
vin                                           78160               66.02
fuel_cons_comb_l100_km                        76538               64.65
original_market                               72766               61.47
co2_emission_grper_wltp_km                    71927               60.76
primary_fuel                                  58409               49.34
nr_prev_owners                                53568               45.25
body_color_original                           44332               37.45
gears                                         43248               36.53
ratings_count                                 41954               35.44
ratings_average                               41954               35.44
ratings_recommend_percentage                  41954               35.44
envir_standard                                41261               34.85
upholstery_color                              32485               27.44
drive_train                                   27753               23.44
upholstery                                    26745               22.59
paint_type                                    26047               22.00
cylinders                                     24858               21.00
weight_kg                                     24086               20.35
street                                        20328               17.17
seller_company_name                           19817               16.74
cylinders_volume_cc                           12286               10.38
body_color                                    11911               10.06
nr_seats                                       4906                4.14
description                                    4392                3.71
power_hp                                       1612                1.36
power_kw                                       1612                1.36
nr_doors                                       1453                1.23
model                                          1402                1.18
model_version                                   838                0.71
transmission                                    816                0.69
mileage_km_raw                                  644                0.54
mileage_km                                      644                0.54
longitude                                       389                0.33
latitude                                        389                0.33
registration_date                               221                0.19
city                                            108                0.09
fuel_category                                    73                0.06
zip                                              19                0.02
country_code                                     15                0.01
seller_type                                      15                0.01

In [171]:
display(df.iloc[0:5, 0:10])

,id,description,ratings_average,ratings_count,ratings_recommend_percentage,price_currency,price,price_tax_deductible,price_negotiable,price_net
0,001c08bb-96f9-4198-a2c9-39bcab088a08,"Deze Suzuki Swift is maatje S, maar hij valt e...",NaN,NaN,NaN,EUR,22950,True,False,19279.0
1,00918c06-f736-404a-b55a-0ccd1d876129,"Kraftvoll, komfortabel, kompromisslos: BMW X3 ...",NaN,NaN,NaN,EUR,46000,False,False,NaN
2,0083e29f-8030-4478-b662-6dff92e22a06,<strong>Highlights:</strong><br /><ul><li><str...,"4,8",124.0,0.0,EUR,179900,False,False,NaN
3,00617c58-7172-49ff-8dc6-cd876ff5f7e8,Veicolo in promozione con la formula &quot;GUI...,"4,2",253.0,83.0,EUR,70400,True,False,NaN
4,00519a06-60a2-4dea-8431-9ec21add3172,De verkoopprijs van deze auto is inclusief een...,NaN,NaN,NaN,EUR,66999,False,False,NaN

In [172]:
df = df.drop(columns=[
    "price_net",
    "latitude",
    "longitude",
    "ratings_recommend_percentage",
    "vehicle_type",
    "price_currency",
    "has_warranty",
    "warranty",
    "street",
    "mileage_km_raw",
    "price_vat_rate",
    "fuel_cons_comb_l100_km",
    "fuel_cons_city_l100_km",
    "fuel_cons_comb_l100_wltp_km",
    "fuel_cons_electric_comb_l100_wltp_km",
    "co2_emission_grper_wltp_km",
    "is_new",
    "non_smoking",
    "seller_is_dealer",
    "seller_type"
])

display(df.head(3))

,id,description,ratings_average,ratings_count,price,price_tax_deductible,price_negotiable,vin,make,model,...,has_full_service_history,nr_prev_owners,is_rental,envir_standard,original_market,offer_type,country_code,zip,city,seller_company_name
0,001c08bb-96f9-4198-a2c9-39bcab088a08,"Deze Suzuki Swift is maatje S, maar hij valt e...",NaN,NaN,22950,True,False,NaN,Suzuki,Swift,...,False,NaN,False,Euro 6d-TEMP,NaN,U,NL,8801 PN,FRANEKER,Haaima Franeker
1,00918c06-f736-404a-b55a-0ccd1d876129,"Kraftvoll, komfortabel, kompromisslos: BMW X3 ...",NaN,NaN,46000,False,False,NaN,BMW,X3 M,...,True,2.0,False,Euro 6d-TEMP,NaN,U,DE,81476,München,NaN
2,0083e29f-8030-4478-b662-6dff92e22a06,<strong>Highlights:</strong><br /><ul><li><str...,"4,8",124.0,179900,False,False,WP0ZZZ99ZJS168484,Porsche,991,...,True,NaN,False,Euro 6,NaN,U,BE,9830,Sint-Martens-Latem,Garage Vandenberghe

In [173]:
display(df.iloc[:5, 0:10])

,id,description,ratings_average,ratings_count,price,price_tax_deductible,price_negotiable,vin,make,model
0,001c08bb-96f9-4198-a2c9-39bcab088a08,"Deze Suzuki Swift is maatje S, maar hij valt e...",NaN,NaN,22950,True,False,NaN,Suzuki,Swift
1,00918c06-f736-404a-b55a-0ccd1d876129,"Kraftvoll, komfortabel, kompromisslos: BMW X3 ...",NaN,NaN,46000,False,False,NaN,BMW,X3 M
2,0083e29f-8030-4478-b662-6dff92e22a06,<strong>Highlights:</strong><br /><ul><li><str...,"4,8",124.0,179900,False,False,WP0ZZZ99ZJS168484,Porsche,991
3,00617c58-7172-49ff-8dc6-cd876ff5f7e8,Veicolo in promozione con la formula &quot;GUI...,"4,2",253.0,70400,True,False,NaN,Audi,A6
4,00519a06-60a2-4dea-8431-9ec21add3172,De verkoopprijs van deze auto is inclusief een...,NaN,NaN,66999,False,False,NaN,Porsche,Panamera

In [174]:
display(df.iloc[:5, 10:20])

,model_version,german_hsn_tsn,mileage_km,registration_date,production_year,body_type,nr_seats,nr_doors,body_color,paint_type
0,1.2 Style Smart Hybrid | Navigatie | Cruise co...,NaN,"10,500 km",01-12-2024,NaN,Compact,5.0,5.0,Black,Metallic
1,M40i xDrive | nahezu Vollausstattung | Top-Zus...,NaN,"55,609 km",01-03-2020,NaN,Off-Road/Pick-up,5.0,5.0,Blue,Metallic
2,.2 GT3 TOURING / MANUAL / CHRONO / LIFT / BOSE,NaN,"18,200 km",01-04-2018,NaN,Coupe,2.0,2.0,Blue,Metallic
3,Avant TDI 150 kW S tronic quattro,NaN,10 km,01-06-2025,NaN,Station wagon,5.0,5.0,White,Metallic
4,Sport Turismo 2.9 4 E-Hybrid 10 Years Edition ...,NaN,"74,602 km",01-11-2019,NaN,Station wagon,5.0,5.0,Black,Metallic

In [175]:
df.iloc[0:2,41:70]

,equipment_safety,is_used,is_preregistered,had_accident,has_full_service_history,nr_prev_owners,is_rental,envir_standard,original_market,offer_type,country_code,zip,city,seller_company_name
0,"['ABS', 'Adaptive Cruise Control', 'Alarm syst...",True,False,False,False,NaN,False,Euro 6d-TEMP,NaN,U,NL,8801 PN,FRANEKER,Haaima Franeker
1,"['ABS', 'Adaptive Cruise Control', 'Adaptive h...",True,False,False,True,2.0,False,Euro 6d-TEMP,NaN,U,DE,81476,München,NaN

In [177]:
df["offer_type"].value_counts(dropna=False)

offer_type
U    114127
N      4252
A         3
Name: count, dtype: int64

In [178]:
df= df.drop(columns=["offer_type"])
df.head(2)

,id,description,ratings_average,ratings_count,price,price_tax_deductible,price_negotiable,vin,make,model,...,had_accident,has_full_service_history,nr_prev_owners,is_rental,envir_standard,original_market,country_code,zip,city,seller_company_name
0,001c08bb-96f9-4198-a2c9-39bcab088a08,"Deze Suzuki Swift is maatje S, maar hij valt e...",NaN,NaN,22950,True,False,NaN,Suzuki,Swift,...,False,False,NaN,False,Euro 6d-TEMP,NaN,NL,8801 PN,FRANEKER,Haaima Franeker
1,00918c06-f736-404a-b55a-0ccd1d876129,"Kraftvoll, komfortabel, kompromisslos: BMW X3 ...",NaN,NaN,46000,False,False,NaN,BMW,X3 M,...,False,True,2.0,False,Euro 6d-TEMP,NaN,DE,81476,München,NaN

In [179]:
df= df.drop(columns=["vin"])
df.head(2)

,id,description,ratings_average,ratings_count,price,price_tax_deductible,price_negotiable,make,model,model_version,...,had_accident,has_full_service_history,nr_prev_owners,is_rental,envir_standard,original_market,country_code,zip,city,seller_company_name
0,001c08bb-96f9-4198-a2c9-39bcab088a08,"Deze Suzuki Swift is maatje S, maar hij valt e...",NaN,NaN,22950,True,False,Suzuki,Swift,1.2 Style Smart Hybrid | Navigatie | Cruise co...,...,False,False,NaN,False,Euro 6d-TEMP,NaN,NL,8801 PN,FRANEKER,Haaima Franeker
1,00918c06-f736-404a-b55a-0ccd1d876129,"Kraftvoll, komfortabel, kompromisslos: BMW X3 ...",NaN,NaN,46000,False,False,BMW,X3 M,M40i xDrive | nahezu Vollausstattung | Top-Zus...,...,False,True,2.0,False,Euro 6d-TEMP,NaN,DE,81476,München,NaN

In [180]:
df.iloc[:, :10].isnull().sum()

id                          0
description              4392
ratings_average         41954
ratings_count           41954
price                       0
price_tax_deductible        0
price_negotiable            0
make                        0
model                    1402
model_version             838
dtype: int64

In [181]:
display(df[df["description"].isnull()])

,id,description,ratings_average,ratings_count,price,price_tax_deductible,price_negotiable,make,model,model_version,...,had_accident,has_full_service_history,nr_prev_owners,is_rental,envir_standard,original_market,country_code,zip,city,seller_company_name
24,004ecfa0-28fe-4fc6-8da0-3082194ee548,NaN,"4,4",10.0,127900,False,False,Porsche,Macan,Turbo,...,False,True,1.0,False,NaN,NaN,AT,9010,Klagenfurt,Porsche Inter Auto GmbH & Co KG
26,0090a9db-4ccf-4cee-9f1f-da75a4981778,NaN,"4,3",16.0,89904,False,False,Audi,S6,e-tron,...,False,True,1.0,False,NaN,NaN,AT,6714,Nüziders,Rudi Lins GmbH & Co KG
92,00abe496-09aa-4c6a-91c2-c58edccacf45,NaN,NaN,NaN,41500,False,False,Audi,Q3,Sportback 40 2.0 tdi S line edition quattro 190cv,...,False,False,NaN,False,NaN,NaN,IT,39014,Postal,NaN
96,0057190d-3f87-4568-ae33-9942f38155f9,NaN,"4,5",17.0,124900,False,False,Porsche,Cayenne,E-Hybrid,...,False,True,1.0,False,NaN,NaN,AT,1230,Wien,Porsche Inter Auto GmbH & Co KG
112,00887d6d-79c4-4d47-acb8-f5fb76809c3a,NaN,NaN,NaN,1500,False,False,Suzuki,Grand Vitara,5p 1.9 ddis,...,False,False,NaN,False,NaN,NaN,IT,60030,Serra De Conti,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118285,ffd189d8-7fe4-425b-8747-b077c811a9cf,NaN,NaN,NaN,42500,False,False,Porsche,Macan,GTS Aut.,...,False,True,NaN,False,NaN,NaN,ES,21004,Huelva,NaN
118322,ffe0e002-e19b-4654-9bef-945df920e9c1,NaN,"3,8",11.0,369950,False,False,Porsche,992,GT3 RS,...,False,False,1.0,False,Euro 6e,Italy,IT,178,Roma - RM,Centro Porsche Roma - Hauswagen Srl
118340,ffecac4b-85d9-4d38-a8de-494646178c85,NaN,NaN,NaN,57900,False,True,Porsche,Cayenne,Cayenne Coupe 2019 Coupe 3.0 e-hybrid tiptronic,...,False,False,NaN,False,Euro 6e,NaN,IT,52041,Arezzo,NaN
118346,ffebb06e-3411-4c2b-921e-a74f1a8408b7,NaN,NaN,NaN,40000,False,False,Porsche,Macan,Macan GTS PDK,...,False,True,1.0,False,Euro 6,NaN,DE,93051,Regensburg,NaN
118369,fff7d868-944b-4261-8d11-2b3e5898d675,NaN,NaN,NaN,20250,False,True,BMW,320,320i Touring Aut.M Sport,...,False,True,3.0,False,NaN,NaN,DE,85301,Schweitenkirchen,NaN

In [182]:
df["description"] = df["description"].fillna("Not Available")

In [183]:
df.iloc[:, :10].isnull().sum()

id                          0
description                 0
ratings_average         41954
ratings_count           41954
price                       0
price_tax_deductible        0
price_negotiable            0
make                        0
model                    1402
model_version             838
dtype: int64

In [184]:
df["ratings_average"] = df["ratings_average"].fillna("Not Rated")
df["ratings_count"] = df["ratings_count"].fillna(0)

In [185]:
df.iloc[:, :10].isnull().sum()

id                         0
description                0
ratings_average            0
ratings_count              0
price                      0
price_tax_deductible       0
price_negotiable           0
make                       0
model                   1402
model_version            838
dtype: int64

In [187]:
display(df[df["model"].isnull() & df["model_version"].isnull()])

,id,description,ratings_average,ratings_count,price,price_tax_deductible,price_negotiable,make,model,model_version,...,had_accident,has_full_service_history,nr_prev_owners,is_rental,envir_standard,original_market,country_code,zip,city,seller_company_name
587,01373794-c398-417b-bf14-e92e00fa2555,<br /><br /><br /><br /><hr /><strong>Ehemalig...,"4,0",280.0,60480,True,False,Audi,NaN,NaN,...,False,False,1.0,False,Euro 6d,NaN,DE,51373,Leverkusen,Automobil Zentrum Leverkusen GmbH & Co. KG
1296,02d85d24-9db3-4493-96ec-f86069a7de90,<br /><strong>Herstellerinformation Audi:</str...,"4,5",39.0,80911,True,False,Audi,NaN,NaN,...,False,True,1.0,False,NaN,NaN,DE,14482,Potsdam,Audi Zentrum Potsdam
5377,0b950635-677d-4935-9ce1-ddaf759ce9b1,<ul><li>550 - Trekhaak</li><li>421 - Automatis...,"0,0",0.0,131799,True,False,Mercedes-Benz,NaN,NaN,...,False,False,NaN,False,Euro 6,NaN,BE,2930,Brasschaat,Hedin Automotive Brasschaat
7248,0f945cbb-b819-4234-a234-9d54b1d4868e,<ul><li>P47 - Parkeerpakket</li><li>840 - Zij-...,"0,0",0.0,142757,True,False,Mercedes-Benz,NaN,NaN,...,False,False,NaN,False,Euro 6,NaN,BE,9406,Ninove,Hedin Automotive Ninove
15739,22385b69-e1b5-4b42-b516-db6bc43b439e,Not Available,Not Rated,0.0,1000,False,True,Suzuki,NaN,NaN,...,False,True,3.0,False,NaN,NaN,BE,1089,Bruxelles,NaN
20119,2bbe6c6c-43a9-488c-ab0f-04d594b51ae0,<ul><li>550 - Trekhaak</li><li>421 - Automatis...,"0,0",0.0,131484,True,False,Mercedes-Benz,NaN,NaN,...,False,False,NaN,False,Euro 6,NaN,BE,3190,Boortmeerbeek,Hedin Automotive Boortmeerbeek
27750,3c50300b-ba6f-4c1e-ae84-8c55b6761157,<ul><li>550 - Trekhaak</li><li>421 - Automatis...,"0,0",0.0,128024,True,False,Mercedes-Benz,NaN,NaN,...,False,False,NaN,False,Euro 6,NaN,BE,9406,Ninove,Hedin Automotive Ninove
40213,56c1732b-edc6-4070-80d3-1b9eb31a1efc,<br /><strong>Herstellerinformation Audi:</str...,"4,5",39.0,69411,True,False,Audi,NaN,NaN,...,False,True,1.0,False,NaN,NaN,DE,14482,Potsdam,Audi Zentrum Potsdam
43108,5cdaf28a-c216-4e66-9dc4-3871b62d1278,- Révision complète à joru chez BMW 24/09/2025...,"0,0",0.0,39990,False,False,BMW,NaN,NaN,...,False,True,NaN,False,NaN,NaN,FR,52100,Saint-Dizier,TRANSAKAUTO SAINT-DIZIER
49404,6a964bc0-6528-418f-ad15-e0f6ab15b7c5,<ul><li>P47 - Parkeerpakket</li><li>840 - Zij-...,"0,0",0.0,142757,True,False,Mercedes-Benz,NaN,NaN,...,False,False,NaN,False,Euro 6,NaN,BE,9100,Sint Niklaas,Hedin Automotive Sint-Niklaas
50733,6d8a33de-f078-4bcf-a626-d86918996abc,<ul><li>P47 - Parkeerpakket</li><li>840 - Zij-...,"0,0",0.0,146568,True,False,Mercedes-Benz,NaN,NaN,...,False,False,NaN,False,Euro 6,NaN,BE,9160,Lokeren,Hedin Automotive Lokeren
51987,7036a6af-0dc6-4da3-8810-e3dfd0203afb,<ul><li>P47 - Parkeerpakket</li><li>840 - Zij-...,"0,0",0.0,146568,True,False,Mercedes-Benz,NaN,NaN,...,False,False,NaN,False,Euro 6,NaN,BE,2500,Lier,Hedin Automotive Lier
54137,74bb1f84-f213-4f6f-8fad-7c7ed8da7b26,<ul><li>P47 - Parkeerpakket</li><li>840 - Zij-...,"0,0",0.0,142757,True,False,Mercedes-Benz,NaN,NaN,...,False,False,NaN,False,Euro 6,NaN,BE,9830,Sint-Martens-Latem,Hedin Automotive Sint-Martens-Latem
55205,77258daf-5617-4cb8-a85c-5764ef4cd505,SIMPLICICAR NICE - 76 AVENUE DES BAUMETTES - 0...,"0,0",0.0,117777,False,False,Mercedes-Benz,NaN,NaN,...,False,False,NaN,False,NaN,NaN,FR,6000,Nice,Simplicicar Nice
59048,7f32c184-c603-4189-a488-9d6e19e33a3e,<ul><li>P47 - Parkeerpakket</li><li>840 - Zij-...,"0,0",0.0,123709,True,False,Mercedes-Benz,NaN,NaN,...,False,False,NaN,False,Euro 6,NaN,BE,9100,Sint Niklaas,Hedin Automotive Sint-Niklaas
62268,861cf057-3ea4-475d-8ad7-f76a7bcf4329,<ul><li>P44 - Parkeerpakket</li><li>P20 - Rija...,"0,0",0.0,173356,True,False,Mercedes-Benz,NaN,NaN,...,False,False,NaN,False,Euro 6,NaN,BE,9160,Lokeren,Hedin Automotive Lokeren
68914,94613c4a-6449-4acd-b697-2be421de9b88,<ul><li>P47 - Parkeerpakket</li><li>840 - Zij-...,"0,0",0.0,129396,True,False,Mercedes-Benz,NaN,NaN,...,False,False,NaN,False,Euro 6,NaN,BE,9160,Lokeren,Hedin Automotive Lokeren
82969,b2d50da7-8034-4783-9cde-48ff1a4a3e8c,<ul><li>P47 - Parkeerpakket</li><li>840 - Zij-...,"0,0",0.0,142757,True,False,Mercedes-Benz,NaN,NaN,...,False,False,NaN,False,Euro 6,NaN,BE,2500,Lier,Hedin Automotive Lier
83369,b3ad0264-0292-48a3-b780-e9c995f9aded,<ul><li>P47 - Parkeerpakket</li><li>840 - Zij-...,"0,0",0.0,142757,True,False,Mercedes-Benz,NaN,NaN,...,False,False,NaN,False,Euro 6,NaN,BE,3190,Boortmeerbeek,Hedin Automotive Boortmeerbeek
84963,b72b119b-220d-4f17-b730-a2a8016e7ff1,ESPECTACULAR ROLLS-ROYCE <br />. Año: 1937<br ...,Not Rated,0.0,98000,False,False,Rolls-Royce,NaN,NaN,...,False,False,NaN,False,NaN,NaN,ES,28223,Pozuelo de Alarcón,NaN
96061,cf5f504b-70f5-43a8-9343-f776cee51dff,<ul><li>P47 - Parkeerpakket</li><li>840 - Zij-...,"0,0",0.0,142757,True,False,Mercedes-Benz,NaN,NaN,...,False,False,NaN,False,Euro 6,NaN,BE,9320,Aalst,Hedin Automotive Aalst
98797,d54233fb-7d3c-4ffa-a89b-97faa73f0b5d,Fahrzeug-Nr.: A067578<br /><hr /><strong></str...,"4,3",33.0,75930,True,False,Audi,NaN,NaN,...,False,False,1.0,False,Euro 6,Germany,DE,52511,Geilenkirchen,Audi Zentrum Aachen Jacobs Automobile GmbH

In [188]:
df=df.dropna(subset=["model","model_version"])

In [189]:
print("Remaining rows:", len(df))
print(df[["model", "model_version"]].isnull().sum())

Remaining rows: 116164
model            0
model_version    0
dtype: int64

In [190]:
display(df.iloc[:2, 10:21])

,german_hsn_tsn,mileage_km,registration_date,production_year,body_type,nr_seats,nr_doors,body_color,paint_type,body_color_original,upholstery
0,NaN,"10,500 km",01-12-2024,NaN,Compact,5.0,5.0,Black,Metallic,Super black pearl metallic (zw,Cloth
1,NaN,"55,609 km",01-03-2020,NaN,Off-Road/Pick-up,5.0,5.0,Blue,Metallic,NaN,Full leather

In [191]:
display(df.iloc[:, 10:21].isnull().sum())

german_hsn_tsn         86142
mileage_km               579
registration_date        199
production_year        94346
body_type                  0
nr_seats                4592
nr_doors                1305
body_color             11680
paint_type             25427
body_color_original    43643
upholstery             26108
dtype: int64

In [192]:
df=df.dropna(subset=["registration_date"])

In [193]:
display(df.iloc[:, 10:21].isnull().sum())

german_hsn_tsn         85962
mileage_km               547
registration_date          0
production_year        94205
body_type                  0
nr_seats                4586
nr_doors                1300
body_color             11662
paint_type             25384
body_color_original    43586
upholstery             26055
dtype: int64

In [194]:
df["german_hsn_tsn"] = df["german_hsn_tsn"].fillna("Not Available")

In [195]:
df["production_year"] = df["production_year"].fillna("Not Available")

In [196]:

columns_to_fill = [
    "nr_seats",
    "nr_doors",
    "body_color",
    "paint_type",
    "body_color_original",
    "upholstery"
]

df[columns_to_fill] = df[columns_to_fill].fillna("Not Available")

In [197]:
display(df.iloc[:, 10:21].isnull().sum())

german_hsn_tsn           0
mileage_km             547
registration_date        0
production_year          0
body_type                0
nr_seats                 0
nr_doors                 0
body_color               0
paint_type               0
body_color_original      0
upholstery               0
dtype: int64

In [198]:
df=df.dropna(subset=["mileage_km"])

In [199]:
display(df.iloc[:, 10:21].isnull().sum())

german_hsn_tsn         0
mileage_km             0
registration_date      0
production_year        0
body_type              0
nr_seats               0
nr_doors               0
body_color             0
paint_type             0
body_color_original    0
upholstery             0
dtype: int64

In [200]:
display(df.iloc[:, 22:33].isnull().sum())

power_kw                1498
power_hp                1498
transmission             702
gears                  41714
drive_train            26354
cylinders              22989
cylinders_volume_cc    11282
weight_kg              22445
has_particle_filter        0
fuel_category             66
primary_fuel           57379
dtype: int64

In [201]:

text_columns = [
    "power_hp",
    "gears" ,
    "cylinders" ,
    "cylinders_volume_cc",
    "weight_kg"
]

df[text_columns] = df[text_columns].fillna("Not Available")

In [203]:

text_columns = [
    "drive_train",
    "primary_fuel",
    "power_hp",
    "gears" ,
    "cylinders" ,
    "cylinders_volume_cc",
    "weight_kg"
]

df[text_columns] = df[text_columns].fillna("Not Available")

In [132]:
display(df.iloc[:, 22:33].isnull().sum())

power_kw               9
power_hp               0
transmission           0
gears                  0
drive_train            0
cylinders              0
cylinders_volume_cc    0
weight_kg              0
has_particle_filter    0
fuel_category          0
primary_fuel           0
dtype: int64

In [204]:
df["power_kw"] = df["power_kw"].fillna("Not Available")

In [205]:
display(df.iloc[:, 22:33].isnull().sum())

power_kw                 0
power_hp                 0
transmission           702
gears                    0
drive_train              0
cylinders                0
cylinders_volume_cc      0
weight_kg                0
has_particle_filter      0
fuel_category           66
primary_fuel             0
dtype: int64

In [207]:
df["transmission"] = df["transmission"].fillna("Not Available")

In [208]:
df = df.dropna(subset=["fuel_category"])

In [209]:
display(df.iloc[:, 34:50].isnull().sum())

electric_range_city_km       114735
fuel_cons_highway_l100_km    115352
co2_emission_grper_km         90861
equipment_comfort                 0
equipment_entertainment           0
equipment_extra                   0
equipment_safety                  0
is_used                           0
is_preregistered                  0
had_accident                      0
has_full_service_history          0
nr_prev_owners                51758
is_rental                         0
envir_standard                39777
original_market               70909
country_code                     14
dtype: int64

In [210]:
df = df.drop(columns=[
    "electric_range_city_km",
    "fuel_cons_highway_l100_km",
    "co2_emission_grper_km",
    "envir_standard"
])

In [211]:
display(df.iloc[:, 34:50].isnull().sum())

equipment_comfort               0
equipment_entertainment         0
equipment_extra                 0
equipment_safety                0
is_used                         0
is_preregistered                0
had_accident                    0
has_full_service_history        0
nr_prev_owners              51758
is_rental                       0
original_market             70909
country_code                   14
zip                            18
city                          105
seller_company_name         19455
dtype: int64

In [212]:
df["nr_prev_owners"] = df["nr_prev_owners"].fillna("Not Available")

In [213]:
df["original_market"] = df["original_market"].fillna("Not Available")

In [214]:
df["seller_company_name"] = df["seller_company_name"].fillna("Not Available")

In [215]:
display(df.iloc[:, 34:50].isnull().sum())

equipment_comfort             0
equipment_entertainment       0
equipment_extra               0
equipment_safety              0
is_used                       0
is_preregistered              0
had_accident                  0
has_full_service_history      0
nr_prev_owners                0
is_rental                     0
original_market               0
country_code                 14
zip                          18
city                        105
seller_company_name           0
dtype: int64

In [216]:
df = df.dropna(subset=["country_code", "zip", "city"])

In [218]:
df.info()

<class 'pandas.DataFrame'>
Index: 115246 entries, 0 to 118381
Data columns (total 49 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id                        115246 non-null  str
 1   description               115246 non-null  str
 2   ratings_average           115246 non-null  str
 3   ratings_count             115246 non-null  float64
 4   price                     115246 non-null  int64
 5   price_tax_deductible      115246 non-null  bool
 6   price_negotiable          115246 non-null  bool
 7   make                      115246 non-null  str
 8   model                     115246 non-null  str
 9   model_version             115246 non-null  str
 10  german_hsn_tsn            115246 non-null  str
 11  mileage_km                115246 non-null  str
 12  registration_date         115246 non-null  str
 13  production_year           115246 non-null  object
 14  body_type                 115246 non-null  str
 15  nr_seats                  115246 non-null  object
 16  nr_doors                  115246 non-null  object
 17  body_color                115246 non-null  str
 18  paint_type                115246 non-null  str
 19  body_color_original       115246 non-null  str
 20  upholstery                115246 non-null  str
 21  upholstery_color          83710 non-null   str
 22  power_kw                  115246 non-null  object
 23  power_hp                  115246 non-null  object
 24  transmission              115246 non-null  str
 25  gears                     115246 non-null  object
 26  drive_train               115246 non-null  str
 27  cylinders                 115246 non-null  object
 28  cylinders_volume_cc       115246 non-null  object
 29  weight_kg                 115246 non-null  str
 30  has_particle_filter       115246 non-null  bool
 31  fuel_category             115246 non-null  str
 32  primary_fuel              115246 non-null  str
 33  electric_range_km         12176 non-null   float64
 34  equipment_comfort         115246 non-null  str
 35  equipment_entertainment   115246 non-null  str
 36  equipment_extra           115246 non-null  str
 37  equipment_safety          115246 non-null  str
 38  is_used                   115246 non-null  bool
 39  is_preregistered          115246 non-null  bool
 40  had_accident              115246 non-null  bool
 41  has_full_service_history  115246 non-null  bool
 42  nr_prev_owners            115246 non-null  object
 43  is_rental                 115246 non-null  bool
 44  original_market           115246 non-null  str
 45  country_code              115246 non-null  str
 46  zip                       115246 non-null  str
 47  city                      115246 non-null  str
 48  seller_company_name       115246 non-null  str
dtypes: bool(8), float64(2), int64(1), object(9), str(29)
memory usage: 37.8+ MB

In [219]:
df["upholstery_color"] = df["upholstery_color"].fillna("Not Available")

In [220]:
df["electric_range_km"] = df["electric_range_km"].fillna("Not Available")

In [221]:
df=df.dropna(subset=["city"])

In [222]:
df.info()

<class 'pandas.DataFrame'>
Index: 115246 entries, 0 to 118381
Data columns (total 49 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id                        115246 non-null  str
 1   description               115246 non-null  str
 2   ratings_average           115246 non-null  str
 3   ratings_count             115246 non-null  float64
 4   price                     115246 non-null  int64
 5   price_tax_deductible      115246 non-null  bool
 6   price_negotiable          115246 non-null  bool
 7   make                      115246 non-null  str
 8   model                     115246 non-null  str
 9   model_version             115246 non-null  str
 10  german_hsn_tsn            115246 non-null  str
 11  mileage_km                115246 non-null  str
 12  registration_date         115246 non-null  str
 13  production_year           115246 non-null  object
 14  body_type                 115246 non-null  str
 15  nr_seats                  115246 non-null  object
 16  nr_doors                  115246 non-null  object
 17  body_color                115246 non-null  str
 18  paint_type                115246 non-null  str
 19  body_color_original       115246 non-null  str
 20  upholstery                115246 non-null  str
 21  upholstery_color          115246 non-null  str
 22  power_kw                  115246 non-null  object
 23  power_hp                  115246 non-null  object
 24  transmission              115246 non-null  str
 25  gears                     115246 non-null  object
 26  drive_train               115246 non-null  str
 27  cylinders                 115246 non-null  object
 28  cylinders_volume_cc       115246 non-null  object
 29  weight_kg                 115246 non-null  str
 30  has_particle_filter       115246 non-null  bool
 31  fuel_category             115246 non-null  str
 32  primary_fuel              115246 non-null  str
 33  electric_range_km         115246 non-null  object
 34  equipment_comfort         115246 non-null  str
 35  equipment_entertainment   115246 non-null  str
 36  equipment_extra           115246 non-null  str
 37  equipment_safety          115246 non-null  str
 38  is_used                   115246 non-null  bool
 39  is_preregistered          115246 non-null  bool
 40  had_accident              115246 non-null  bool
 41  has_full_service_history  115246 non-null  bool
 42  nr_prev_owners            115246 non-null  object
 43  is_rental                 115246 non-null  bool
 44  original_market           115246 non-null  str
 45  country_code              115246 non-null  str
 46  zip                       115246 non-null  str
 47  city                      115246 non-null  str
 48  seller_company_name       115246 non-null  str
dtypes: bool(8), float64(1), int64(1), object(10), str(29)
memory usage: 37.8+ MB

In [223]:
display(df.iloc[:, :].isnull().sum())

id                          0
description                 0
ratings_average             0
ratings_count               0
price                       0
price_tax_deductible        0
price_negotiable            0
make                        0
model                       0
model_version               0
german_hsn_tsn              0
mileage_km                  0
registration_date           0
production_year             0
body_type                   0
nr_seats                    0
nr_doors                    0
body_color                  0
paint_type                  0
body_color_original         0
upholstery                  0
upholstery_color            0
power_kw                    0
power_hp                    0
transmission                0
gears                       0
drive_train                 0
cylinders                   0
cylinders_volume_cc         0
weight_kg                   0
has_particle_filter         0
fuel_category               0
primary_fuel                0
electric_range_km           0
equipment_comfort           0
equipment_entertainment     0
equipment_extra             0
equipment_safety            0
is_used                     0
is_preregistered            0
had_accident                0
has_full_service_history    0
nr_prev_owners              0
is_rental                   0
original_market             0
country_code                0
zip                         0
city                        0
seller_company_name         0
dtype: int64

In [224]:
numeric_columns = [
    "price",
    "mileage_km",
    "production_year",
    "nr_seats",
    "nr_doors",
    "power_kw",
    "power_hp",
    "gears",
    "cylinders",
    "cylinders_volume_cc",
    "weight_kg",
    "electric_range_km",
    "nr_prev_owners"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [225]:
df["registration_date"] = pd.to_datetime(
    df["registration_date"],
    errors="coerce"
)

In [226]:
df.info()

<class 'pandas.DataFrame'>
Index: 115246 entries, 0 to 118381
Data columns (total 49 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id                        115246 non-null  str
 1   description               115246 non-null  str
 2   ratings_average           115246 non-null  str
 3   ratings_count             115246 non-null  float64
 4   price                     115246 non-null  int64
 5   price_tax_deductible      115246 non-null  bool
 6   price_negotiable          115246 non-null  bool
 7   make                      115246 non-null  str
 8   model                     115246 non-null  str
 9   model_version             115246 non-null  str
 10  german_hsn_tsn            115246 non-null  str
 11  mileage_km                0 non-null       float64
 12  registration_date         115246 non-null  datetime64[us]
 13  production_year           21328 non-null   float64
 14  body_type                 115246 non-null  str
 15  nr_seats                  111144 non-null  float64
 16  nr_doors                  113964 non-null  float64
 17  body_color                115246 non-null  str
 18  paint_type                115246 non-null  str
 19  body_color_original       115246 non-null  str
 20  upholstery                115246 non-null  str
 21  upholstery_color          115246 non-null  str
 22  power_kw                  113753 non-null  float64
 23  power_hp                  113753 non-null  float64
 24  transmission              115246 non-null  str
 25  gears                     73601 non-null   float64
 26  drive_train               115246 non-null  str
 27  cylinders                 92323 non-null   float64
 28  cylinders_volume_cc       103994 non-null  float64
 29  weight_kg                 0 non-null       float64
 30  has_particle_filter       115246 non-null  bool
 31  fuel_category             115246 non-null  str
 32  primary_fuel              115246 non-null  str
 33  electric_range_km         12176 non-null   float64
 34  equipment_comfort         115246 non-null  str
 35  equipment_entertainment   115246 non-null  str
 36  equipment_extra           115246 non-null  str
 37  equipment_safety          115246 non-null  str
 38  is_used                   115246 non-null  bool
 39  is_preregistered          115246 non-null  bool
 40  had_accident              115246 non-null  bool
 41  has_full_service_history  115246 non-null  bool
 42  nr_prev_owners            63583 non-null   float64
 43  is_rental                 115246 non-null  bool
 44  original_market           115246 non-null  str
 45  country_code              115246 non-null  str
 46  zip                       115246 non-null  str
 47  city                      115246 non-null  str
 48  seller_company_name       115246 non-null  str
dtypes: bool(8), datetime64[us](1), float64(13), int64(1), str(26)
memory usage: 37.8 MB

In [229]:
print(df[["mileage_km", "weight_kg"]].dtypes)

mileage_km    float64
weight_kg     float64
dtype: object

In [231]:
df.shape

(115246, 49)

In [235]:
df_original = pd.read_csv("Car_prices_list_uncleaned.csv")

In [236]:
df["mileage_km"] = df_original.loc[df.index, "mileage_km"]
df["weight_kg"] = df_original.loc[df.index, "weight_kg"]

In [237]:
df.shape

(115246, 49)

In [243]:
df.info()

<class 'pandas.DataFrame'>
Index: 115246 entries, 0 to 118381
Data columns (total 49 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id                        115246 non-null  str
 1   description               115246 non-null  str
 2   ratings_average           115246 non-null  str
 3   ratings_count             115246 non-null  float64
 4   price                     115246 non-null  int64
 5   price_tax_deductible      115246 non-null  bool
 6   price_negotiable          115246 non-null  bool
 7   make                      115246 non-null  str
 8   model                     115246 non-null  str
 9   model_version             115246 non-null  str
 10  german_hsn_tsn            115246 non-null  str
 11  mileage_km                115246 non-null  str
 12  registration_date         115246 non-null  datetime64[us]
 13  production_year           21328 non-null   float64
 14  body_type                 115246 non-null  str
 15  nr_seats                  111144 non-null  float64
 16  nr_doors                  113964 non-null  float64
 17  body_color                115246 non-null  str
 18  paint_type                115246 non-null  str
 19  body_color_original       115246 non-null  str
 20  upholstery                115246 non-null  str
 21  upholstery_color          115246 non-null  str
 22  power_kw                  113753 non-null  float64
 23  power_hp                  113753 non-null  float64
 24  transmission              115246 non-null  str
 25  gears                     73601 non-null   float64
 26  drive_train               115246 non-null  str
 27  cylinders                 92323 non-null   float64
 28  cylinders_volume_cc       103994 non-null  float64
 29  weight_kg                 92868 non-null   str
 30  has_particle_filter       115246 non-null  bool
 31  fuel_category             115246 non-null  str
 32  primary_fuel              115246 non-null  str
 33  electric_range_km         12176 non-null   float64
 34  equipment_comfort         115246 non-null  str
 35  equipment_entertainment   115246 non-null  str
 36  equipment_extra           115246 non-null  str
 37  equipment_safety          115246 non-null  str
 38  is_used                   115246 non-null  bool
 39  is_preregistered          115246 non-null  bool
 40  had_accident              115246 non-null  bool
 41  has_full_service_history  115246 non-null  bool
 42  nr_prev_owners            63583 non-null   float64
 43  is_rental                 115246 non-null  bool
 44  original_market           115246 non-null  str
 45  country_code              115246 non-null  str
 46  zip                       115246 non-null  str
 47  city                      115246 non-null  str
 48  seller_company_name       115246 non-null  str
dtypes: bool(8), datetime64[us](1), float64(11), int64(1), str(28)
memory usage: 37.8 MB

In [244]:
columns_to_fill = [
    "production_year",
    "nr_seats",
    "nr_doors",
    "power_kw",
    "power_hp",
    "gears",
    "cylinders",
    "cylinders_volume_cc",
    "weight_kg",
    "electric_range_km",
    "nr_prev_owners"
]

df[columns_to_fill] = df[columns_to_fill].fillna("Not Available")

In [238]:
display(df[["mileage_km", "weight_kg"]].head(100))

    mileage_km weight_kg
0    10,500 km    894 kg
1    55,609 km  1,945 kg
2    18,200 km  1,760 kg
3        10 km  2,075 kg
4    74,602 km  2,165 kg
..         ...       ...
96   10,780 km  2,586 kg
97    5,000 km  2,020 kg
98   78,000 km    880 kg
99   90,000 km  1,870 kg
100  81,000 km  1,655 kg

[100 rows x 2 columns]

In [245]:
df.info()

<class 'pandas.DataFrame'>
Index: 115246 entries, 0 to 118381
Data columns (total 49 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id                        115246 non-null  str
 1   description               115246 non-null  str
 2   ratings_average           115246 non-null  str
 3   ratings_count             115246 non-null  float64
 4   price                     115246 non-null  int64
 5   price_tax_deductible      115246 non-null  bool
 6   price_negotiable          115246 non-null  bool
 7   make                      115246 non-null  str
 8   model                     115246 non-null  str
 9   model_version             115246 non-null  str
 10  german_hsn_tsn            115246 non-null  str
 11  mileage_km                115246 non-null  str
 12  registration_date         115246 non-null  datetime64[us]
 13  production_year           115246 non-null  object
 14  body_type                 115246 non-null  str
 15  nr_seats                  115246 non-null  object
 16  nr_doors                  115246 non-null  object
 17  body_color                115246 non-null  str
 18  paint_type                115246 non-null  str
 19  body_color_original       115246 non-null  str
 20  upholstery                115246 non-null  str
 21  upholstery_color          115246 non-null  str
 22  power_kw                  115246 non-null  object
 23  power_hp                  115246 non-null  object
 24  transmission              115246 non-null  str
 25  gears                     115246 non-null  object
 26  drive_train               115246 non-null  str
 27  cylinders                 115246 non-null  object
 28  cylinders_volume_cc       115246 non-null  object
 29  weight_kg                 115246 non-null  str
 30  has_particle_filter       115246 non-null  bool
 31  fuel_category             115246 non-null  str
 32  primary_fuel              115246 non-null  str
 33  electric_range_km         115246 non-null  object
 34  equipment_comfort         115246 non-null  str
 35  equipment_entertainment   115246 non-null  str
 36  equipment_extra           115246 non-null  str
 37  equipment_safety          115246 non-null  str
 38  is_used                   115246 non-null  bool
 39  is_preregistered          115246 non-null  bool
 40  had_accident              115246 non-null  bool
 41  has_full_service_history  115246 non-null  bool
 42  nr_prev_owners            115246 non-null  object
 43  is_rental                 115246 non-null  bool
 44  original_market           115246 non-null  str
 45  country_code              115246 non-null  str
 46  zip                       115246 non-null  str
 47  city                      115246 non-null  str
 48  seller_company_name       115246 non-null  str
dtypes: bool(8), datetime64[us](1), float64(1), int64(1), object(10), str(28)
memory usage: 37.8+ MB

In [246]:

df.to_csv("cars_cleaned_complete.csv", index=False)

In [247]:
import os
print(os.getcwd())

c:\Users\shiva\WBS\streamlit_project\car_price_app

In [248]:
import os
print(os.path.exists("cars_cleaned_complete.csv"))

True